[window]
opacity=1.0
padding={x = 4, y = 4}
decorations="None"
startup_mode="SimpleFullscreen"

[colors.primary]
background="#1e1e2e" #11111b

[font]
normal={family='AdwaitaMono Nerd Font Propo', style='Regular'}
